name: Java CI with Maven
on:
  push
env:
  JWT_SECRET: ${{secrets.JWT_SECRET}}
jobs:
 build-auth-service:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
     java-version: '17'
     distribution: 'temurin'
     cache: maven
  - name: Build Auth Service with Maven
    run: |
     cd authusers
     mvn test -D$JWT_SECRET
 build-todolist-service:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
     java-version: '17'
     distribution: 'temurin'
     cache: maven
  - name: Build todolist Service with Maven
    run: |
     cd todolist
     mvn test -D$JWT_SECRET
 build-notifications-service:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
     java-version: '17'
     distribution: 'temurin'
     cache: maven
  - name: Build notifications Service with Maven
    run: |
     cd notifications
     mvn test -D$JWT_SECRET
