name: Hello world
on: 
  schedule:
    - cron:  '*/10 * * * *'
env:
  JWT_SECRET: "secret"
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run:
        echo Hello World
  A:
    runs-on: ubuntu-latest
    needs: hello-world-job
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run:
        echo Hello World2
  B:
    runs-on: ubuntu-latest
    needs: hello-world-job
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run:
        echo Hello World3
